NOTE: 一時的にdependabotを停止する
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    reviewers:
      - hatsu38
    open-pull-requests-limit: 0
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - hatsu38
    open-pull-requests-limit: 0
    schedule:
      interval: monthly
